**Imports & Configurations**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pt
import seaborn as sns
import os
import psutil

print(f"free memory: {psutil.virtual_memory().available / 1024 ** 3:.2f} GB")

pd.set_option("display.max_columns", 50)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.float_format", "{:.2f}".format)

DATA_DIR = "../dataset"
FIGURES_DIR = "../outputs/figures"
os.makedirs(FIGURES_DIR, exist_ok=True)

SEED = 42

free memory: 1.69 GB

**Load and inspect every file**

In [2]:
files = {
    "application_train": "application_train.csv",
    "application_test": "application_test.csv",
    "bureau":            "bureau.csv",
    "bureau_balance":    "bureau_balance.csv",
    "previous_application": "previous_application.csv",
    "pos_cash":          "POS_CASH_balance.csv",
    "installments":      "installments_payments.csv",
    "credit_card":       "credit_card_balance.csv"
}

col_des_df = pd.DataFrame(pd.read_csv(os.path.join(DATA_DIR, "HomeCredit_columns_description.csv"), encoding="cp1252"))

**Inspect Application Train Table**

In [3]:
df = pd.DataFrame(pd.read_csv(os.path.join(DATA_DIR, files['application_train'])))
print("====== First data ======")
display(df.head())

print("====== Data Types ======")
display(df.dtypes.to_dict())

# Types, nulls, and column descriptions
summary = pd.DataFrame({
    "column": df.columns,
    "types": df.dtypes,
    "nulls": df.isnull().sum(),
    "null_pct": (df.isnull().sum() / len(df) * 100).round(2)
}).reset_index(drop=True)

summary = summary.merge(
    col_des_df[["Row", "Description"]],
    left_on="column",
    right_on="Row",
    how="left"
).drop(columns=["Row"])

summary = (
    summary[summary["null_pct"] > 0]
    .sort_values("null_pct", ascending=False)
    .style.set_properties(
        subset=["column", "Description"],
        **{"text-align": "left"}
    )
)

display(summary)

====== First data ======

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,...,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.00,406597.50,24700.50,351000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.02,-9461,-637,-3648.00,-2120,NaN,1,1,0,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,1.00
1,100003,0,Cash loans,F,N,N,0,270000.00,1293502.50,35698.50,1129500.00,Family,State servant,Higher education,Married,House / apartment,0.00,-16765,-1188,-1186.00,-291,NaN,1,1,0,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00
2,100004,0,Revolving loans,M,Y,Y,0,67500.00,135000.00,6750.00,135000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.01,-19046,-225,-4260.00,-2531,26.00,1,1,1,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00
3,100006,0,Cash loans,F,N,Y,0,135000.00,312682.50,29686.50,297000.00,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.01,-19005,-3039,-9833.00,-2437,NaN,1,1,0,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.00,513000.00,21865.50,513000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.03,-19932,-3038,-4311.00,-3458,NaN,1,1,0,...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00

====== Data Types ======

{'SK_ID_CURR': dtype('int64'),
 'TARGET': dtype('int64'),
 'NAME_CONTRACT_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'CODE_GENDER': <StringDtype(storage='python', na_value=nan)>,
 'FLAG_OWN_CAR': <StringDtype(storage='python', na_value=nan)>,
 'FLAG_OWN_REALTY': <StringDtype(storage='python', na_value=nan)>,
 'CNT_CHILDREN': dtype('int64'),
 'AMT_INCOME_TOTAL': dtype('float64'),
 'AMT_CREDIT': dtype('float64'),
 'AMT_ANNUITY': dtype('float64'),
 'AMT_GOODS_PRICE': dtype('float64'),
 'NAME_TYPE_SUITE': <StringDtype(storage='python', na_value=nan)>,
 'NAME_INCOME_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'NAME_EDUCATION_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'NAME_FAMILY_STATUS': <StringDtype(storage='python', na_value=nan)>,
 'NAME_HOUSING_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'REGION_POPULATION_RELATIVE': dtype('float64'),
 'DAYS_BIRTH': dtype('int64'),
 'DAYS_EMPLOYED': dtype('int64'),
 'DAYS_REGISTRATION': dtype('float64'),
 'DAYS_ID_PUBLISH': dtype('int64'),
 'OWN_CAR_AGE': dtype('float64'),
 'FLAG_MOBIL': dtype('int64'),
 'FLAG_EMP_PHONE': dtype('int64'),
 'FLAG_WORK_PHONE': dtype('int64'),
 'FLAG_CONT_MOBILE': dtype('int64'),
 'FLAG_PHONE': dtype('int64'),
 'FLAG_EMAIL': dtype('int64'),
 'OCCUPATION_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'CNT_FAM_MEMBERS': dtype('float64'),
 'REGION_RATING_CLIENT': dtype('int64'),
 'REGION_RATING_CLIENT_W_CITY': dtype('int64'),
 'WEEKDAY_APPR_PROCESS_START': <StringDtype(storage='python', na_value=nan)>,
 'HOUR_APPR_PROCESS_START': dtype('int64'),
 'REG_REGION_NOT_LIVE_REGION': dtype('int64'),
 'REG_REGION_NOT_WORK_REGION': dtype('int64'),
 'LIVE_REGION_NOT_WORK_REGION': dtype('int64'),
 'REG_CITY_NOT_LIVE_CITY': dtype('int64'),
 'REG_CITY_NOT_WORK_CITY': dtype('int64'),
 'LIVE_CITY_NOT_WORK_CITY': dtype('int64'),
 'ORGANIZATION_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'EXT_SOURCE_1': dtype('float64'),
 'EXT_SOURCE_2': dtype('float64'),
 'EXT_SOURCE_3': dtype('float64'),
 'APARTMENTS_AVG': dtype('float64'),
 'BASEMENTAREA_AVG': dtype('float64'),
 'YEARS_BEGINEXPLUATATION_AVG': dtype('float64'),
 'YEARS_BUILD_AVG': dtype('float64'),
 'COMMONAREA_AVG': dtype('float64'),
 'ELEVATORS_AVG': dtype('float64'),
 'ENTRANCES_AVG': dtype('float64'),
 'FLOORSMAX_AVG': dtype('float64'),
 'FLOORSMIN_AVG': dtype('float64'),
 'LANDAREA_AVG': dtype('float64'),
 'LIVINGAPARTMENTS_AVG': dtype('float64'),
 'LIVINGAREA_AVG': dtype('float64'),
 'NONLIVINGAPARTMENTS_AVG': dtype('float64'),
 'NONLIVINGAREA_AVG': dtype('float64'),
 'APARTMENTS_MODE': dtype('float64'),
 'BASEMENTAREA_MODE': dtype('float64'),
 'YEARS_BEGINEXPLUATATION_MODE': dtype('float64'),
 'YEARS_BUILD_MODE': dtype('float64'),
 'COMMONAREA_MODE': dtype('float64'),
 'ELEVATORS_MODE': dtype('float64'),
 'ENTRANCES_MODE': dtype('float64'),
 'FLOORSMAX_MODE': dtype('float64'),
 'FLOORSMIN_MODE': dtype('float64'),
 'LANDAREA_MODE': dtype('float64'),
 'LIVINGAPARTMENTS_MODE': dtype('float64'),
 'LIVINGAREA_MODE': dtype('float64'),
 'NONLIVINGAPARTMENTS_MODE': dtype('float64'),
 'NONLIVINGAREA_MODE': dtype('float64'),
 'APARTMENTS_MEDI': dtype('float64'),
 'BASEMENTAREA_MEDI': dtype('float64'),
 'YEARS_BEGINEXPLUATATION_MEDI': dtype('float64'),
 'YEARS_BUILD_MEDI': dtype('float64'),
 'COMMONAREA_MEDI': dtype('float64'),
 'ELEVATORS_MEDI': dtype('float64'),
 'ENTRANCES_MEDI': dtype('float64'),
 'FLOORSMAX_MEDI': dtype('float64'),
 'FLOORSMIN_MEDI': dtype('float64'),
 'LANDAREA_MEDI': dtype('float64'),
 'LIVINGAPARTMENTS_MEDI': dtype('float64'),
 'LIVINGAREA_MEDI': dtype('float64'),
 'NONLIVINGAPARTMENTS_MEDI': dtype('float64'),
 'NONLIVINGAREA_MEDI': dtype('float64'),
 'FONDKAPREMONT_MODE': <StringDtype(storage='python', na_value=nan)>,
 'HOUSETYPE_MODE': <StringDtype(storage='python', na_value=nan)>,
 'TOTALAREA_MODE': dtype('float64'),
 'WALLSMATERIAL_MODE': <StringDtype(storage='python', na_value=nan)>,
 'EMERGENCYSTATE_MODE': <StringDtype(storage='python', na_value=nan)>,
 'OBS_30_CNT_SOCIAL_CIRCLE': dtype('float64'),
 'DEF_30_CNT_SOCIAL_CIRCLE': dtype('float64'),
 'OBS_60_CNT_SOCIAL_CIRCLE': dtype('float64'),
 'DEF_60_CNT_SOCIAL_CIRCLE': dtype('float64'),
 'DAYS_LAST_PHONE_CHANGE': dtype('float64'),
 'FLAG_DOCUMENT_2': dtype('int64'),
 'FLAG_DOCUMENT_3': dtype('int64'),
 'FLAG_DOCUMENT_4': dtype('int64'),
 'FLAG_DOCUMENT_5': dtype('int64'),
 'FLAG_DOCUMENT_6': dtype('int64'),
 'FLAG_DOCUMENT_7': dtype('int64'),
 'FLAG_DOCUMENT_8': dtype('int64'),
 'FLAG_DOCUMENT_9': dtype('int64'),
 'FLAG_DOCUMENT_10': dtype('int64'),
 'FLAG_DOCUMENT_11': dtype('int64'),
 'FLAG_DOCUMENT_12': dtype('int64'),
 'FLAG_DOCUMENT_13': dtype('int64'),
 'FLAG_DOCUMENT_14': dtype('int64'),
 'FLAG_DOCUMENT_15': dtype('int64'),
 'FLAG_DOCUMENT_16': dtype('int64'),
 'FLAG_DOCUMENT_17': dtype('int64'),
 'FLAG_DOCUMENT_18': dtype('int64'),
 'FLAG_DOCUMENT_19': dtype('int64'),
 'FLAG_DOCUMENT_20': dtype('int64'),
 'FLAG_DOCUMENT_21': dtype('int64'),
 'AMT_REQ_CREDIT_BUREAU_HOUR': dtype('float64'),
 'AMT_REQ_CREDIT_BUREAU_DAY': dtype('float64'),
 'AMT_REQ_CREDIT_BUREAU_WEEK': dtype('float64'),
 'AMT_REQ_CREDIT_BUREAU_MON': dtype('float64'),
 'AMT_REQ_CREDIT_BUREAU_QRT': dtype('float64'),
 'AMT_REQ_CREDIT_BUREAU_YEAR': dtype('float64')}

**Inspect Application Test Table**

In [4]:
df = pd.DataFrame(pd.read_csv(os.path.join(DATA_DIR, files['application_train'])))
print("====== First data ======")
display(df.head())

print("====== Data Types ======")
display(df.dtypes.to_dict())

# Types & Nulls
summary = pd.DataFrame({
    "column": df.columns,
    "types": df.dtypes,
    "nulls": df.isnull().sum(),
    "null_pct": (df.isnull().sum() / len(df) * 100).round(2)
}).reset_index(drop=True)

summary = summary.merge(
    col_des_df[["Row", "Description"]],
    left_on="column",
    right_on="Row",
    how="left"
).drop(columns=["Row"])

summary = (
    summary[summary["null_pct"] > 0]
    .sort_values("null_pct", ascending=False)
    .style.set_properties(
        subset=["column", "Description"],
        **{"text-align": "left"}
    )
)

display(summary)

====== First data ======

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,...,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.00,406597.50,24700.50,351000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.02,-9461,-637,-3648.00,-2120,NaN,1,1,0,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,1.00
1,100003,0,Cash loans,F,N,N,0,270000.00,1293502.50,35698.50,1129500.00,Family,State servant,Higher education,Married,House / apartment,0.00,-16765,-1188,-1186.00,-291,NaN,1,1,0,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00
2,100004,0,Revolving loans,M,Y,Y,0,67500.00,135000.00,6750.00,135000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.01,-19046,-225,-4260.00,-2531,26.00,1,1,1,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00
3,100006,0,Cash loans,F,N,Y,0,135000.00,312682.50,29686.50,297000.00,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.01,-19005,-3039,-9833.00,-2437,NaN,1,1,0,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.00,513000.00,21865.50,513000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.03,-19932,-3038,-4311.00,-3458,NaN,1,1,0,...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00

====== Data Types ======

{'SK_ID_CURR': dtype('int64'),
 'TARGET': dtype('int64'),
 'NAME_CONTRACT_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'CODE_GENDER': <StringDtype(storage='python', na_value=nan)>,
 'FLAG_OWN_CAR': <StringDtype(storage='python', na_value=nan)>,
 'FLAG_OWN_REALTY': <StringDtype(storage='python', na_value=nan)>,
 'CNT_CHILDREN': dtype('int64'),
 'AMT_INCOME_TOTAL': dtype('float64'),
 'AMT_CREDIT': dtype('float64'),
 'AMT_ANNUITY': dtype('float64'),
 'AMT_GOODS_PRICE': dtype('float64'),
 'NAME_TYPE_SUITE': <StringDtype(storage='python', na_value=nan)>,
 'NAME_INCOME_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'NAME_EDUCATION_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'NAME_FAMILY_STATUS': <StringDtype(storage='python', na_value=nan)>,
 'NAME_HOUSING_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'REGION_POPULATION_RELATIVE': dtype('float64'),
 'DAYS_BIRTH': dtype('int64'),
 'DAYS_EMPLOYED': dtype('int64'),
 'DAYS_REGISTRATION': dtype('float64'),
 'DAYS_ID_PUBLISH': dtype('int64'),
 'OWN_CAR_AGE': dtype('float64'),
 'FLAG_MOBIL': dtype('int64'),
 'FLAG_EMP_PHONE': dtype('int64'),
 'FLAG_WORK_PHONE': dtype('int64'),
 'FLAG_CONT_MOBILE': dtype('int64'),
 'FLAG_PHONE': dtype('int64'),
 'FLAG_EMAIL': dtype('int64'),
 'OCCUPATION_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'CNT_FAM_MEMBERS': dtype('float64'),
 'REGION_RATING_CLIENT': dtype('int64'),
 'REGION_RATING_CLIENT_W_CITY': dtype('int64'),
 'WEEKDAY_APPR_PROCESS_START': <StringDtype(storage='python', na_value=nan)>,
 'HOUR_APPR_PROCESS_START': dtype('int64'),
 'REG_REGION_NOT_LIVE_REGION': dtype('int64'),
 'REG_REGION_NOT_WORK_REGION': dtype('int64'),
 'LIVE_REGION_NOT_WORK_REGION': dtype('int64'),
 'REG_CITY_NOT_LIVE_CITY': dtype('int64'),
 'REG_CITY_NOT_WORK_CITY': dtype('int64'),
 'LIVE_CITY_NOT_WORK_CITY': dtype('int64'),
 'ORGANIZATION_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'EXT_SOURCE_1': dtype('float64'),
 'EXT_SOURCE_2': dtype('float64'),
 'EXT_SOURCE_3': dtype('float64'),
 'APARTMENTS_AVG': dtype('float64'),
 'BASEMENTAREA_AVG': dtype('float64'),
 'YEARS_BEGINEXPLUATATION_AVG': dtype('float64'),
 'YEARS_BUILD_AVG': dtype('float64'),
 'COMMONAREA_AVG': dtype('float64'),
 'ELEVATORS_AVG': dtype('float64'),
 'ENTRANCES_AVG': dtype('float64'),
 'FLOORSMAX_AVG': dtype('float64'),
 'FLOORSMIN_AVG': dtype('float64'),
 'LANDAREA_AVG': dtype('float64'),
 'LIVINGAPARTMENTS_AVG': dtype('float64'),
 'LIVINGAREA_AVG': dtype('float64'),
 'NONLIVINGAPARTMENTS_AVG': dtype('float64'),
 'NONLIVINGAREA_AVG': dtype('float64'),
 'APARTMENTS_MODE': dtype('float64'),
 'BASEMENTAREA_MODE': dtype('float64'),
 'YEARS_BEGINEXPLUATATION_MODE': dtype('float64'),
 'YEARS_BUILD_MODE': dtype('float64'),
 'COMMONAREA_MODE': dtype('float64'),
 'ELEVATORS_MODE': dtype('float64'),
 'ENTRANCES_MODE': dtype('float64'),
 'FLOORSMAX_MODE': dtype('float64'),
 'FLOORSMIN_MODE': dtype('float64'),
 'LANDAREA_MODE': dtype('float64'),
 'LIVINGAPARTMENTS_MODE': dtype('float64'),
 'LIVINGAREA_MODE': dtype('float64'),
 'NONLIVINGAPARTMENTS_MODE': dtype('float64'),
 'NONLIVINGAREA_MODE': dtype('float64'),
 'APARTMENTS_MEDI': dtype('float64'),
 'BASEMENTAREA_MEDI': dtype('float64'),
 'YEARS_BEGINEXPLUATATION_MEDI': dtype('float64'),
 'YEARS_BUILD_MEDI': dtype('float64'),
 'COMMONAREA_MEDI': dtype('float64'),
 'ELEVATORS_MEDI': dtype('float64'),
 'ENTRANCES_MEDI': dtype('float64'),
 'FLOORSMAX_MEDI': dtype('float64'),
 'FLOORSMIN_MEDI': dtype('float64'),
 'LANDAREA_MEDI': dtype('float64'),
 'LIVINGAPARTMENTS_MEDI': dtype('float64'),
 'LIVINGAREA_MEDI': dtype('float64'),
 'NONLIVINGAPARTMENTS_MEDI': dtype('float64'),
 'NONLIVINGAREA_MEDI': dtype('float64'),
 'FONDKAPREMONT_MODE': <StringDtype(storage='python', na_value=nan)>,
 'HOUSETYPE_MODE': <StringDtype(storage='python', na_value=nan)>,
 'TOTALAREA_MODE': dtype('float64'),
 'WALLSMATERIAL_MODE': <StringDtype(storage='python', na_value=nan)>,
 'EMERGENCYSTATE_MODE': <StringDtype(storage='python', na_value=nan)>,
 'OBS_30_CNT_SOCIAL_CIRCLE': dtype('float64'),
 'DEF_30_CNT_SOCIAL_CIRCLE': dtype('float64'),
 'OBS_60_CNT_SOCIAL_CIRCLE': dtype('float64'),
 'DEF_60_CNT_SOCIAL_CIRCLE': dtype('float64'),
 'DAYS_LAST_PHONE_CHANGE': dtype('float64'),
 'FLAG_DOCUMENT_2': dtype('int64'),
 'FLAG_DOCUMENT_3': dtype('int64'),
 'FLAG_DOCUMENT_4': dtype('int64'),
 'FLAG_DOCUMENT_5': dtype('int64'),
 'FLAG_DOCUMENT_6': dtype('int64'),
 'FLAG_DOCUMENT_7': dtype('int64'),
 'FLAG_DOCUMENT_8': dtype('int64'),
 'FLAG_DOCUMENT_9': dtype('int64'),
 'FLAG_DOCUMENT_10': dtype('int64'),
 'FLAG_DOCUMENT_11': dtype('int64'),
 'FLAG_DOCUMENT_12': dtype('int64'),
 'FLAG_DOCUMENT_13': dtype('int64'),
 'FLAG_DOCUMENT_14': dtype('int64'),
 'FLAG_DOCUMENT_15': dtype('int64'),
 'FLAG_DOCUMENT_16': dtype('int64'),
 'FLAG_DOCUMENT_17': dtype('int64'),
 'FLAG_DOCUMENT_18': dtype('int64'),
 'FLAG_DOCUMENT_19': dtype('int64'),
 'FLAG_DOCUMENT_20': dtype('int64'),
 'FLAG_DOCUMENT_21': dtype('int64'),
 'AMT_REQ_CREDIT_BUREAU_HOUR': dtype('float64'),
 'AMT_REQ_CREDIT_BUREAU_DAY': dtype('float64'),
 'AMT_REQ_CREDIT_BUREAU_WEEK': dtype('float64'),
 'AMT_REQ_CREDIT_BUREAU_MON': dtype('float64'),
 'AMT_REQ_CREDIT_BUREAU_QRT': dtype('float64'),
 'AMT_REQ_CREDIT_BUREAU_YEAR': dtype('float64')}

**Inspect Bureau Table**

In [5]:
df = pd.DataFrame(pd.read_csv(os.path.join(DATA_DIR, files['bureau'])))
print("====== First Data ======")
display(df.head())

print("====== Data Types ======")
display(df.dtypes.to_dict())

# Types & Nulls
summary = pd.DataFrame({
    "column": df.columns,
    "types": df.dtypes,
    "nulls": df.isnull().sum(),
    "null_pct": (df.isnull().sum() / len(df) * 100).round(2)
})

summary = summary.merge(
    col_des_df[["Row", "Description"]],
    left_on="column",
    right_on="Row",
    how="left"
).drop(columns=["Row"])

summary = (summary[summary['null_pct'] > 0].sort_values('null_pct', ascending=False).style.set_properties(
    subset=['column', 'Description'], **{"text-align": "left"}
))

display(summary)

====== First Data ======

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.00,-153.00,NaN,0,91323.00,0.00,NaN,0.00,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.00,NaN,NaN,0,225000.00,171342.00,NaN,0.00,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.00,NaN,NaN,0,464323.50,NaN,NaN,0.00,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.00,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.00,NaN,77674.50,0,2700000.00,NaN,NaN,0.00,Consumer credit,-21,NaN

====== Data Types ======

{'SK_ID_CURR': dtype('int64'),
 'SK_ID_BUREAU': dtype('int64'),
 'CREDIT_ACTIVE': <StringDtype(storage='python', na_value=nan)>,
 'CREDIT_CURRENCY': <StringDtype(storage='python', na_value=nan)>,
 'DAYS_CREDIT': dtype('int64'),
 'CREDIT_DAY_OVERDUE': dtype('int64'),
 'DAYS_CREDIT_ENDDATE': dtype('float64'),
 'DAYS_ENDDATE_FACT': dtype('float64'),
 'AMT_CREDIT_MAX_OVERDUE': dtype('float64'),
 'CNT_CREDIT_PROLONG': dtype('int64'),
 'AMT_CREDIT_SUM': dtype('float64'),
 'AMT_CREDIT_SUM_DEBT': dtype('float64'),
 'AMT_CREDIT_SUM_LIMIT': dtype('float64'),
 'AMT_CREDIT_SUM_OVERDUE': dtype('float64'),
 'CREDIT_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'DAYS_CREDIT_UPDATE': dtype('int64'),
 'AMT_ANNUITY': dtype('float64')}

**Inspect Bureau Balance Table**

In [6]:
df = pd.DataFrame(pd.read_csv(os.path.join(DATA_DIR, files['bureau_balance'])))
print("====== First data ======")
display(df.head())

print("====== Data Types ======")
display(df.dtypes.to_dict())

# Types & Nulls
summary = pd.DataFrame({
    "column": df.columns,
    "types": df.dtypes,
    "nulls": df.isnull().sum(),
    "null_pct": (df.isnull().sum() / len(df) * 100).round(2)
}).reset_index(drop=True)

summary = summary.merge(
    col_des_df[["Row", "Description"]],
    left_on="column",
    right_on="Row",
    how="left"
).drop(columns=["Row"])

summary = (summary[summary['null_pct'] > 0]
           .sort_values('null_pct', ascending=False)
           .style.set_properties(subset=["column", "Description"], **{"text-align": "left"}))

display(summary)

====== First data ======

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C

====== Data Types ======

{'SK_ID_BUREAU': dtype('int64'),
 'MONTHS_BALANCE': dtype('int64'),
 'STATUS': <StringDtype(storage='python', na_value=nan)>}

**Inspect Previous Application Table**

In [7]:
df = pd.DataFrame(pd.read_csv(os.path.join(DATA_DIR, files['previous_application'])))
print("====== First Data ======")
display(df.head())

print("====== Data Types ======")
display(df.dtypes.to_dict())

# Types & Nulls
summary = pd.DataFrame({
    "column": df.columns,
    "types": df.dtypes,
    "nulls": df.isnull().sum(),
    "null_pct": (df.isnull().sum() / len(df) * 100).round(2)
}).reset_index(drop=True)

summary = summary.merge(
    col_des_df[["Row", "Description"]],
    left_on="column",
    right_on="Row",
    how="left"
).drop(columns=["Row"])

summary = (summary[summary["null_pct"] > 0].sort_values("null_pct", ascending=False).style.set_properties(
    subset=["column", "Description"], **{"text-align": "left"}
))

display(summary)

====== First Data ======

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.43,17145.00,17145.00,0.00,17145.00,SATURDAY,15,Y,1,0.00,0.18,0.87,XAP,Approved,-73,Cash through the bank,XAP,NaN,Repeater,Mobile,POS,XNA,Country-wide,35,Connectivity,12.00,middle,POS mobile with interest,365243.00,-42.00,300.00,-42.00,-37.00,0.00
1,2802425,108129,Cash loans,25188.62,607500.00,679671.00,NaN,607500.00,THURSDAY,11,Y,1,NaN,NaN,NaN,XNA,Approved,-164,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Contact center,-1,XNA,36.00,low_action,Cash X-Sell: low,365243.00,-134.00,916.00,365243.00,365243.00,1.00
2,2523466,122040,Cash loans,15060.74,112500.00,136444.50,NaN,112500.00,TUESDAY,11,Y,1,NaN,NaN,NaN,XNA,Approved,-301,Cash through the bank,XAP,"Spouse, partner",Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.00,high,Cash X-Sell: high,365243.00,-271.00,59.00,365243.00,365243.00,1.00
3,2819243,176158,Cash loans,47041.33,450000.00,470790.00,NaN,450000.00,MONDAY,7,Y,1,NaN,NaN,NaN,XNA,Approved,-512,Cash through the bank,XAP,NaN,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.00,middle,Cash X-Sell: middle,365243.00,-482.00,-152.00,-182.00,-177.00,1.00
4,1784265,202054,Cash loans,31924.40,337500.00,404055.00,NaN,337500.00,THURSDAY,9,Y,1,NaN,NaN,NaN,Repairs,Refused,-781,Cash through the bank,HC,NaN,Repeater,XNA,Cash,walk-in,Credit and cash offices,-1,XNA,24.00,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

====== Data Types ======

{'SK_ID_PREV': dtype('int64'),
 'SK_ID_CURR': dtype('int64'),
 'NAME_CONTRACT_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'AMT_ANNUITY': dtype('float64'),
 'AMT_APPLICATION': dtype('float64'),
 'AMT_CREDIT': dtype('float64'),
 'AMT_DOWN_PAYMENT': dtype('float64'),
 'AMT_GOODS_PRICE': dtype('float64'),
 'WEEKDAY_APPR_PROCESS_START': <StringDtype(storage='python', na_value=nan)>,
 'HOUR_APPR_PROCESS_START': dtype('int64'),
 'FLAG_LAST_APPL_PER_CONTRACT': <StringDtype(storage='python', na_value=nan)>,
 'NFLAG_LAST_APPL_IN_DAY': dtype('int64'),
 'RATE_DOWN_PAYMENT': dtype('float64'),
 'RATE_INTEREST_PRIMARY': dtype('float64'),
 'RATE_INTEREST_PRIVILEGED': dtype('float64'),
 'NAME_CASH_LOAN_PURPOSE': <StringDtype(storage='python', na_value=nan)>,
 'NAME_CONTRACT_STATUS': <StringDtype(storage='python', na_value=nan)>,
 'DAYS_DECISION': dtype('int64'),
 'NAME_PAYMENT_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'CODE_REJECT_REASON': <StringDtype(storage='python', na_value=nan)>,
 'NAME_TYPE_SUITE': <StringDtype(storage='python', na_value=nan)>,
 'NAME_CLIENT_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'NAME_GOODS_CATEGORY': <StringDtype(storage='python', na_value=nan)>,
 'NAME_PORTFOLIO': <StringDtype(storage='python', na_value=nan)>,
 'NAME_PRODUCT_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'CHANNEL_TYPE': <StringDtype(storage='python', na_value=nan)>,
 'SELLERPLACE_AREA': dtype('int64'),
 'NAME_SELLER_INDUSTRY': <StringDtype(storage='python', na_value=nan)>,
 'CNT_PAYMENT': dtype('float64'),
 'NAME_YIELD_GROUP': <StringDtype(storage='python', na_value=nan)>,
 'PRODUCT_COMBINATION': <StringDtype(storage='python', na_value=nan)>,
 'DAYS_FIRST_DRAWING': dtype('float64'),
 'DAYS_FIRST_DUE': dtype('float64'),
 'DAYS_LAST_DUE_1ST_VERSION': dtype('float64'),
 'DAYS_LAST_DUE': dtype('float64'),
 'DAYS_TERMINATION': dtype('float64'),
 'NFLAG_INSURED_ON_APPROVAL': dtype('float64')}

**Inspect POS Cash Table**

In [8]:
df = pd.DataFrame(pd.read_csv(os.path.join(DATA_DIR, files['pos_cash'])))
print("====== First Data ======")
display(df.head())

print("====== Data Types ======")
display(df.dtypes.to_dict())

# Types & Nulls
summary = pd.DataFrame({
    "column": df.columns,
    "types": df.dtypes,
    "nulls": df.isnull().sum(),
    "null_pct": (df.isnull().sum() / len(df) * 100).round(2)
})

summary = summary.merge(
    col_des_df[["Row", "Description"]],
    left_on="column",
    right_on="Row",
    how="left"
).drop(columns=["Row"])

summary = (summary[summary["null_pct"] > 0].sort_values("null_pct", ascending=False).style.set_properties(
        subset=["column", "Description"], **{"text-align": "left"}
    ))

display(summary)

====== First Data ======

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.00,45.00,Active,0,0
1,1715348,367990,-33,36.00,35.00,Active,0,0
2,1784872,397406,-32,12.00,9.00,Active,0,0
3,1903291,269225,-35,48.00,42.00,Active,0,0
4,2341044,334279,-35,36.00,35.00,Active,0,0

====== Data Types ======

{'SK_ID_PREV': dtype('int64'),
 'SK_ID_CURR': dtype('int64'),
 'MONTHS_BALANCE': dtype('int64'),
 'CNT_INSTALMENT': dtype('float64'),
 'CNT_INSTALMENT_FUTURE': dtype('float64'),
 'NAME_CONTRACT_STATUS': <StringDtype(storage='python', na_value=nan)>,
 'SK_DPD': dtype('int64'),
 'SK_DPD_DEF': dtype('int64')}

**Inspect Installments Table**

In [9]:
df = pd.DataFrame(pd.read_csv(os.path.join(DATA_DIR, files['installments'])))
print("====== First Data ======")
display(df.head())

print("====== Data Types ======")
display(df.dtypes.to_dict())

# Types & Nulls
summary = pd.DataFrame({
    "column": df.columns,
    "types": df.dtypes,
    "nulls": df.isnull().sum(),
    "null_pct": (df.isnull().sum() / len(df) * 100).round(2)
})

summary = summary.merge(
    col_des_df[["Row", "Description"]],
    left_on="column",
    right_on="Row",
    how="left"
).drop(columns=["Row"])

summary = (summary[summary["null_pct"] > 0].sort_values("null_pct", ascending=False).style.set_properties(
        subset=["column", "Description"], **{"text-align": "left"}
    ))

display(summary)

====== First Data ======

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
0,1054186,161674,1.00,6,-1180.00,-1187.00,6948.36,6948.36
1,1330831,151639,0.00,34,-2156.00,-2156.00,1716.53,1716.53
2,2085231,193053,2.00,1,-63.00,-63.00,25425.00,25425.00
3,2452527,199697,1.00,3,-2418.00,-2426.00,24350.13,24350.13
4,2714724,167756,1.00,2,-1383.00,-1366.00,2165.04,2160.59

====== Data Types ======

{'SK_ID_PREV': dtype('int64'),
 'SK_ID_CURR': dtype('int64'),
 'NUM_INSTALMENT_VERSION': dtype('float64'),
 'NUM_INSTALMENT_NUMBER': dtype('int64'),
 'DAYS_INSTALMENT': dtype('float64'),
 'DAYS_ENTRY_PAYMENT': dtype('float64'),
 'AMT_INSTALMENT': dtype('float64'),
 'AMT_PAYMENT': dtype('float64')}

**Inspect Credit Card Balance Table**

In [10]:
df = pd.DataFrame(pd.read_csv(os.path.join(DATA_DIR, files['credit_card'])))
print("====== First Data ======")
display(df.head())

print("====== Data Types ======")
display(df.dtypes.to_dict())

# Types & Nulls
summary = pd.DataFrame({
    "column": df.columns,
    "types": df.dtypes,
    "nulls": df.isnull().sum(),
    "null_pct": (df.isnull().sum() / len(df) * 100).round(2)
})

summary = summary.merge(
    col_des_df[["Row", "Description"]],
    left_on="column",
    right_on="Row",
    how="left"
).drop(columns=["Row"])

summary = (summary[summary["null_pct"] > 0].sort_values("null_pct", ascending=False).style.set_properties(
        subset=["column", "Description"], **{"text-align": "left"}
    ))

display(summary)

====== First Data ======

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.97,135000,0.00,877.50,0.00,877.50,1700.33,1800.00,1800.00,0.00,0.00,0.00,0.00,1,0.00,1.00,35.00,Active,0,0
1,2582071,363914,-1,63975.56,45000,2250.00,2250.00,0.00,0.00,2250.00,2250.00,2250.00,60175.08,64875.56,64875.56,1.00,1,0.00,0.00,69.00,Active,0,0
2,1740877,371185,-7,31815.22,450000,0.00,0.00,0.00,0.00,2250.00,2250.00,2250.00,26926.42,31460.08,31460.08,0.00,0,0.00,0.00,30.00,Active,0,0
3,1389973,337855,-4,236572.11,225000,2250.00,2250.00,0.00,0.00,11795.76,11925.00,11925.00,224949.29,233048.97,233048.97,1.00,1,0.00,0.00,10.00,Active,0,0
4,1891521,126868,-1,453919.46,450000,0.00,11547.00,0.00,11547.00,22924.89,27000.00,27000.00,443044.40,453919.46,453919.46,0.00,1,0.00,1.00,101.00,Active,0,0

====== Data Types ======

{'SK_ID_PREV': dtype('int64'),
 'SK_ID_CURR': dtype('int64'),
 'MONTHS_BALANCE': dtype('int64'),
 'AMT_BALANCE': dtype('float64'),
 'AMT_CREDIT_LIMIT_ACTUAL': dtype('int64'),
 'AMT_DRAWINGS_ATM_CURRENT': dtype('float64'),
 'AMT_DRAWINGS_CURRENT': dtype('float64'),
 'AMT_DRAWINGS_OTHER_CURRENT': dtype('float64'),
 'AMT_DRAWINGS_POS_CURRENT': dtype('float64'),
 'AMT_INST_MIN_REGULARITY': dtype('float64'),
 'AMT_PAYMENT_CURRENT': dtype('float64'),
 'AMT_PAYMENT_TOTAL_CURRENT': dtype('float64'),
 'AMT_RECEIVABLE_PRINCIPAL': dtype('float64'),
 'AMT_RECIVABLE': dtype('float64'),
 'AMT_TOTAL_RECEIVABLE': dtype('float64'),
 'CNT_DRAWINGS_ATM_CURRENT': dtype('float64'),
 'CNT_DRAWINGS_CURRENT': dtype('int64'),
 'CNT_DRAWINGS_OTHER_CURRENT': dtype('float64'),
 'CNT_DRAWINGS_POS_CURRENT': dtype('float64'),
 'CNT_INSTALMENT_MATURE_CUM': dtype('float64'),
 'NAME_CONTRACT_STATUS': <StringDtype(storage='python', na_value=nan)>,
 'SK_DPD': dtype('int64'),
 'SK_DPD_DEF': dtype('int64')}